### PR TITLE
test: implemented vitest in shared directory

### PR DESCRIPTION
**Pull request by briantkho**
- [x] Look over your code one last time
- [x] Manually test locally all functionality and user interface changes in the browser you expect to be QA'd
- [x] Describe what changes this PR includes
- [x] Post screenshots/gifs for design review, applicable if there are user-facing UI/UX changes
- [x] Fill in QA Notes listing clear, ordered steps for peer, pre-merge QA on the PR

## Description

[Fill in description here]

Closes #x.

## Screenshots/Gifs

[add screenshots/gifs here]

## QA Notes

PR Author Browser Info:

```
**QA Tester Browser Info:** 

## Testing Steps

- [ ] [Add QA steps here]

## Notes

- [ ] [Tester should add any comments, questions, or concerns that pop up during QA]
```

### CODE REVIEW

**Comment by briantkho** [comment]
If this test is good, let me know and I'll implement this on the other directories as well

**Review by AydanGaite — APPROVED** [review]
LGTM

**Comment by o0victor0o** [comment]
> LGTM

Does this mean we install vitest in each package and not in the global package.json?

**Comment by briantkho** [comment]
> each 

@o0victor0o we'll add them into the directories as we go. For now we keep it in the shared directory

**Comment by AydanGaite** [comment]
LGTM means “looks good to me” lmao

**Pull request merged**
